package java_projects;

import java.util.Arrays;

/**
 * 【Java 實作練習：智慧病房監控系統 - 資料相容性處理】
 * 
 * 任務描述：
 * 目前系統正在進行升級，生命徵象的紀錄格式從「單次紀錄」轉換為「連續四次紀錄」。
 * 你需要寫一段 Java 邏輯，能夠判斷輸入的 CSV 字串是「舊格式」還是「新格式」，
 * 並將資料正確填充到一個 3x4 的二維陣列 (doubleGrid[3][4]) 中。
 * 
 * 1. 舊格式 (Legacy)：字串包含 3 個值 (體溫, 脈搏, 血壓)，例如 "36.5,80,120"。
 *    - 處理方式：將該值填入對應組別的第一個欄位 (grid[n][0])，其餘欄位補 0.0。
 * 
 * 2. 新格式 (Detailed)：字串包含 12 個值 (3組 x 4次)，例如 "36.5,36.6,36.4,36.5,80,82,79,81,120,121,119,120"。
 *    - 處理方式：按順序填充入 3x4 網格。
 * 
 * 限制條件：
 * - 必須使用 split(",") 拆分字串。
 * - 必須處理 split 可能產生的空白或缺失欄位 (使用 Double.parseDouble 前要檢查)。
 * - 必須包含陣列長度保險機制，防止 ArrayIndexOutOfBoundsException。
 * 
 * 範例測試資料：
 * String legacyData = "37.2,75,115";
 * String detailedData = "36.5,36.6,,36.5,80,82,79,81,120,121,119,120"; // 注意含空白欄位
 * 
 * @author Takahiro (Challenge generated by Gemini)
 * @date 2026/04/23
 */
public class Q_WardMonitoringChallenge {

    public static void main(String[] args) {
        // TODO: 請在此實作練習邏輯
        
        // 1. 定義接收網格 double[3][4]
        double[][] grid = new double[3][4];
        // 2. 測試舊格式資料處理
        String legacyData = "37.2,75,115";
        String[] legacy = legacyData.split(",");
        System.out.println(Arrays.toString(legacy));
        if(legacy.length == 3) {
            grid[0][0] = Double.parseDouble(legacy[0]);
            grid[1][0] = Double.parseDouble(legacy[1]);
            grid[2][0] = Double.parseDouble(legacy[2]);
        }
        
        // 3. 測試新格式資料處理 (包含空白檢查)
        String detailedData = "36.5,36.6,36.4,36.5,80,82,79,81,120,121,119,120";
        String[] detailed = detailedData.split(",");
        if(detailed.length == 12){
            int index = 0;
            // 在你的 if(detailed.length == 12) 內：
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 4; j++) {
                    // A. 先把字串拿出來，並去掉前後可能的空白
                    String val = detailed[index].trim();
                    
                    // B. 判斷是否為空字串
                    if (!val.isEmpty()) {
                        grid[i][j] = Double.parseDouble(val); // 有資料才轉換
                    } else {
                        grid[i][j] = 0.0; // 如果是空的，手動填入 0.0 (這就是相容性處理)
                    }
                    index++;
                }
            }
        } 
        // 4. 印出網格結果驗證 (請寫在第 69 行)
        System.out.println("--- 最終轉換成果 ---");
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 4; j++) {
                System.out.print(grid[i][j] + "\t");
            }
            System.out.println(); // 印完一橫列就換行
        }
    }
}
